### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#1]

**Comment by ingenthr** [comment]
Brainstorming…
$ cd src/

> list
Cloud Instances
DC Instances
Kubernetes Instances
> open Cloud Instances
> open Azure
> list
[table of couchbase clusters, listing their versions, health]



Imagine I'm an enterprise user…

- Cloud Instances
  - Azure
   - {sdk test}
   - {connectors test}
  - AWS
- DC Instances
- Kubernetes Instances

**Comment by ingenthr** [comment]
Might be done.  @ingenthr to review and see if it's nice.

**Comment by daschl** [comment]
I think the overall navigation and flow is settled by now.
