### ISSUE TITLE
Clusters connect/disconnect

### ISSUE THREAD

**Issue by chvck** [couchbaselabs/couchbase-shell#109]
I want to use couchbase-shell as my default shell but doing so it would be super useful if I could connect and disconnect clusters on the fly in my running shell, maybe with a --save flag so that it updates the config.toml file for next time my shell starts up too.

For instance I spin up short lived clusters on internal infra so I want to be able to just run something like `clusters connect <alias> <address>` (probably with creds and default bucket too) and then when I'm done `clusters disconnect <alias>`.

**Comment by daschl** [comment]
solved via 9ae5430bb29bedc03e476eb0a88ff5f120cc4283
