### ISSUE TITLE
Config: Rename [[clusters]] to [[cluster]] ?

### ISSUE THREAD

**Issue by dnault** [couchbaselabs/couchbase-shell#113]
A minor nit, but perhaps the config section where the user defines a cluster should be the singular "cluster" instead of "clusters".

From the parser's perspective, it is indeed an array of "clusters", but for the user editing the config file, each instance of the repeated table defines a single "cluster".

**Comment by daschl** [comment]
That's a good idea! We should do it before 1.0 GA though @chvck  wdyt?
