### ISSUE TITLE
Libcouchbase

### ISSUE THREAD

**Issue by himanshumps** [couchbaselabs/couchbase-shell#121]
I see that couchbase shell doesn't use libcouchbase as in rust couchbase library. I'd there any plan to provide the same in couchbase rust library ?

**Comment by daschl** [comment]
@himanshumps right now our focus is to get a 1.0 version of cbshell out. Eventually we want to do a pure rust couchbase SDK as well, but before that we probably get a 1.0 of couchbase-rs out on top of libcouchbase (it's just easier to do than a full rewrite).

**Comment by daschl** [comment]
As a side note: the first versions of cbshell were actually on top of libcouchbase, but because of a couple reasons we had to move off of it.

**Comment by daschl** [comment]
Closing this out, since it works as designed right now.
