### ISSUE TITLE
Try to improve error messages

### ISSUE THREAD

**Issue by chvck** [couchbaselabs/couchbase-shell#137]
For example:
```
👤 Administrator 🏠 dev.local in 🗄 travel-sample
> fake --template ./examples/fake-templates/user.tera --num-rows 1000 | doc upsert
error: Error: Unexpected: failed to load config from cluster: Requested resource not found.
```
Here the error could be made much more accessible by adding some information about what's going on i.e. something like "is the target bucket missing?"

**Comment by ingenthr** [comment]
Per discussion with @RekhaDS and I, good to have, but can be deferred if everything else is ready for 1.0.0

**Comment by ingenthr** [comment]
It's possible this is done.  @Westwooo will review this in light of the help changed help handling, see if this is complete or can be gotten to complete for 1.0.
