### ISSUE TITLE
Allow flush against capella

### ISSUE THREAD

**Issue by chvck** [couchbaselabs/couchbase-shell#148]
Seems to now be supported but check both hosted and in-vpc work.

**Comment by ingenthr** [comment]
@RekhaDS  and I talked, not required for v1.0.0 but nice to have if we can.

**Comment by chvck** [comment]
Capella does not seem to allow flush yet.

**Comment by chvck** [comment]
This still might not be possible without API keys but we should take a look anyway.

**Comment by Westwooo** [comment]
Duplicate
