### ISSUE TITLE
Batching doesn't work correctly when TLS is in use

### ISSUE THREAD

**Issue by chvck** [couchbaselabs/couchbase-shell#149]
When TLS is being used then something like a `doc upsert` of a few thousand docs will cause most to timeout. This doesn't happen when TLS is not in use. This means that batching fails against Capella, I can repro this against internal infra also.

**Comment by chvck** [comment]
This doesn't appear to be unique to when TLS is in use but it's far more common.

**Comment by ingenthr** [comment]
Bringing status here from a slack discussion, currently @chvck thinks it may be a bug in @tokio-rs/tokio, but needs to try to narrow it down to a minimum reproduction case.  

Also @chvck says:
"What’s happening here is that the tcp send buffer is getting full and somehow not emptying until the connection is shutdown. Not sure why or how yet…"

**Comment by chvck** [comment]
To add a bit more colour here. I've managed to track this down to the `flush` part of `send` on the `FramedWriter`. The `poll_flush` seems to just hang indefinitely until the connection is closed. If I increase the size of the tcp send buffer or I use smaller batch sizes then the problem goes away.

**Comment by ingenthr** [comment]
Hm.  That sounds like a bit of a concurrency issue of some ilk.  Some kind of lock around the buffer?  I don't know lock debugging in this area though.

Until we can find the actual cause (which isn't likely us) as a workaround can we just increase the TCP send buffer size for 1.0?  It seems that for cbshell, that wouldn't be too terrible.  How big are we talking about?

**Comment by chvck** [comment]
We could also decrease the default batch size and expose an env var or something for the buffer size. I'd have to do some research on the size to use. I just kept adding 0s to a number until the issue stopped...

**Comment by ingenthr** [comment]
Let's change the batch size to ~300, release note it, bump it to post 1.0.

**Comment by chvck** [comment]
I've tested this on Windows, running against Capella with a batch size of 2000 (which reliably causes failures on macos) and everything succeeds. I've tried multiple times and seen no failures. Results from running on Linux would be very interesting.

**Comment by chvck** [comment]
I believe that this is now fixed by moving to tokio-rustls from tokio-native-tls.
