### ISSUE TITLE
Ping crashed upon use, shell exited

### ISSUE THREAD

**Issue by roikatz** [couchbaselabs/couchbase-shell#150]
Issue: ping --bucket bucketName crashes immediately upon usage.
Version: 1.0.0 - beta 3
OS: MacOS 11.6.1

steps to reproduce:
1) make sure you have a local cluster with travel-sample bucket
2) Connect to a local cluster without tls 
$ ./cbsh --disable-tls
3) typed buckets to check connectivity  
$ buckets
<snipped buckets>
4) run the following command
$ping --bucket travel-sample
5) shell crashed, no ping
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/client/kv_client.rs:273:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

--

log
[log.txt](https://github.com/couchbaselabs/couchbase-shell/files/7814661/log.txt)

**Comment by chvck** [comment]
Should now be fixed on HEAD.
