### ISSUE TITLE
include 3rd party licenses

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#157]
We need an SBOM that includes 3rd party licenses and notification.  Also need a license check.

**Comment by ingenthr** [comment]
per discussion, include cyclonedx structured format and a human readable version of these.  also include couchbase software license, if not already done.

**Comment by chvck** [comment]
Cyclonedx bom is now included in the archive as a part of CI/release. It's not terribly human readable though...

**Comment by ingenthr** [comment]
Yes, @RekhaDS and I had a look, and you're correct, it's not terribly human readable.  Since we have Black Duck coverage for this now, let's include the product metadata notices:
https://github.com/couchbase/product-metadata/blob/master/couchbase-shell/blackduck/1.0.0/notices.txt

We will probably need to update some dependencies and update one more time, but it is acceptable to just include this in the repository since it's built after the fact.  It just needs to be updated close to release.

We also noticed the packaging, at least on MacOS, is a little funny now that the CylcloneDX file is included:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/81302/156659848-8f73bbf1-288f-4aab-bee3-ff7332231927.png">

I think that's an unusual structure.  Probably a side effect?

1. Please replace the bom.json with the notices.txt.  Update the README to indicate "Couchbase Shell is made possible through open source components as listed with their licenses in notices.txt"
2. Please include the Couchbase License Agreement and reference it from the README.  https://www.couchbase.com/LA03012021

**Comment by RekhaDS** [comment]
Hello Charlie @chvck - Could you please look at this one? Will help to kickstart the process with Legal.
