### ISSUE TITLE
synchronize log output

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#17]
a log error came up from lcb at the same time cbsh was writing to stdout.  This leads to confusing interleaved text.

![image](https://user-images.githubusercontent.com/81302/81998313-10433980-9607-11ea-9e2b-0b84fd350081.png)

Since lcb has a way to get logging output, that should probbably be surfaced through rust/cbsh and displayed appropriately inline to be more user friendly.

**Comment by daschl** [comment]
that is interesting - we already plug it in with the rust log facade: https://github.com/couchbaselabs/couchbase-rs/blob/master/couchbase/src/io/lcb/callbacks.rs#L607 .. I guess we need to check how we can "bend" the rust log facade to cooperate with whatever nushell is doing
