### ISSUE TITLE
Loading 100 documents into Capella cluster never finishes

### ISSUE THREAD

**Issue by ebenhaber** [couchbaselabs/couchbase-shell#172]
I have some file of 100 json documents which I exported using `cbsh` and the `save` command.

I tried to load the file into a different cluster using `open stats.json | doc upsert`.

When I try to load the file into a Capella cluster, some data is loaded, but the command never finishes (and I waited more than an hour).

**Problem 1**: It is not acceptable for the upsert to hang with no error message.

When I try to load the file into an on-prem cluster, some of the data is loaded, but some of the documents failed:

```
> open stats.json | doc upsert
╭───┬───────────┬─────────┬────────┬───────────────┬───────────╮
│ # │ processed │ success │ failed │   failures    │  cluster  │
├───┼───────────┼─────────┼────────┼───────────────┼───────────┤
│ 0 │       100 │      79 │     21 │ [table 1 row] │ phonehome │
╰───┴───────────┴─────────┴────────┴───────────────┴───────────╯
```

**Problem 2:** It's really hard to figure out why the command failed, I have to create a complex pipe expression.

```
> open stats.json | doc upsert | first 1 | get failures 
╭───┬─────────────╮
│ # │ fail reason │
├───┼─────────────┤
│ 0 │ timeout     │
╰───┴─────────────╯
```

Is there some easier way to report errors? This is especially problematic, since it appears that I have to run the command again to extract the errors.

**Problem 3:** Your default timeout is probably way too low if loading 100 documents exceeds the timeout. When I set the timeout to 10m, I was able to load the documents into the on-prem cluster. However, even with a 30m timeout of the Capella cluster, I cannot load the 100 documents, it just hangs.

**Comment by chvck** [comment]
I believe that this is now fixed. Seems to have been an issue with TLS where the tcp buffer/queue wasn't being flushed correctly - I've now changed the dependency that we use for TLS and it looks like it's working.
