### ISSUE TITLE
Cryptic error when loading data into Capella

### ISSUE THREAD

**Issue by ebenhaber** [couchbaselabs/couchbase-shell#183]
I'm trying to migrate some data from an on-prem cluster to Capella.

The process is a script that runs a query on the on-prem cluster, saves the result to a file, then loads the file into the cappella cluster.

I have tested the process on small amounts of data, and it works fine.

I ran the process on a larger sample of the data (size about 325MB), and I get the following error messages:

`thread 'tokio-runtime-worker' panicked at 'split_to out of bounds: 27 <= 25', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.1.0/src/bytes_mut.rs:362:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'split_to out of bounds: 27 <= 25', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.1.0/src/bytes_mut.rs:362:9`

Since the data is being saved by cbsh, it seems that it ought to be able to load the data again.

**Comment by chvck** [comment]
Should now be fixed.
