### ISSUE TITLE
Rename "kv" commands to "data" (or possible "document")

### ISSUE THREAD

**Issue by krugster** [couchbaselabs/couchbase-shell#19]
My initial reaction was:
-it feels a bit like "inside baseball" that Steve keeps harping on :slightly_smiling_face:
-It creates a bit of confusion/mismatch with the "Data" service
-it also pigeon-holes the operations into "key-value" rather than also being "document"

**Comment by mgroves** [comment]
I lean towards agreement. When there's an acronym that's maybe not well known, I prefer to be explicit. Maybe "keyvalue" instead of "kv"?

**Comment by krugster** [comment]
Definitely agree with being explicit, but "keyvalue" is still a mismatch with what the server setup is (data service) and is still the wrong connotation since it leans the user towards thinking of simple "key value stores" which tend not to support JSON parsing, etc.

**Comment by ingenthr** [comment]
Wanting to keep this short, @daschl and I talked about this and we think perhaps "doc" is a good replacement. 

The oddity here is that there are things like stats.  "doc stats".   

Suggestion here is that we go with doc for document operations and data with things that are specific to the data service.  Thus, "doc get" and "data stats".

**Comment by daschl** [comment]
Fixed on master. kv is now doc and a new data stats command added.
