### ISSUE TITLE
Change version number to match nushell

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#212]
We should change our version number to match nushell.  Currently 0.75.0 on nushell.  We can just match the dot-minor (second position) so we would be 0.75.0.  If we update we would either bump the dot-minor or the dot-micro, depending on if we pick up the nushell version.

Couchbase Shell version prior to 1.0 is basically:

```
0.75.0
^  ^ ^
|  | |
|  | - Last position follows any of our changes
|  - Follows underlying nushell version
- Also follows nushell version, but may be updated when we get to 1.0
```

That said, we may update to 1.0.0 prior to nushell hitting 1.0 if it meets our business goals.  That would imply that we may need to do a 2.0 if there are breaking changes.  @RekhaDS and I think that's okay and we will manage the support policy within this.

**Comment by chvck** [comment]
As a part of this we should update CI so that it can do releases (and tagging) automatically, including adding all the artefacts to the release.
