### ISSUE TITLE
Improve config file creation

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#238]
I used a recent build and the config file creation could be improved I think.

Here's my interaction:
```
ingenthr@ingenthr-mbp Downloads % ./cbsh
No config file found
Would you like to create one now (Y/n)?
Y
Please enter an identifier for the default database:
mbp
Please enter connection string:
couchbase://mymac.local/abucket
Please enter username:
Administrator
Please enter password:
password
Please enter default bucket:
abucket
Please enter default scope:
_default
Please enter default collection:
_default
Please enter directory for config file (.cbsh/):
~/.cbsh
Writing config to "~/.cbsh/config"
INFO: Thanks for trying CBSH!
👤 Administrator 🏠 mbp in 🗄 cbjiraUsers._default._default 
```

A few observations:
- It wasn't really a connection string, since I gave one to the bucket level, but that wasn't acceptable.  :)
- We should probably not echo back the password
- Can we stop at the default bucket?
- Perhaps we can give an example of a connection string when asking for one?

**Comment by ingenthr** [comment]
Also, note that I entered ~/.cbsh/ for the directory, but that didn't work:
```
Please enter directory for config file (.cbsh/):
~/.cbsh/
Writing config to "~/.cbsh/config"
```

I don't know what it did, but it didn't write there.

Taking the default worked though.

**Comment by ingenthr** [comment]
Well, it kind of worked:
```
Please enter directory for config file (.cbsh/):

Writing config to "/Users/ingenthr/Downloads/.cbsh/config"
```

Note that includes where I'm running it from.

**Comment by chvck** [comment]
I believe that this is now fixed as of https://github.com/couchbaselabs/couchbase-shell/commit/f894f267663f848efd4defd1bfba87f8a732b8b2.

**Comment by ingenthr** [comment]
Nice, thank you.
