### ISSUE TITLE
Remove expect and unwrap from codebase

### ISSUE THREAD

**Issue by chvck** [couchbaselabs/couchbase-shell#255]
If we're going to fail something we should do it gracefully and at least attempt to give the user some information about why we've failed. We shouldn't just panic.

**Comment by chvck** [comment]
expect and unwrap in main.rs are probably ok, these happen at startup. unwrap when taking a lock also ok, this can only happen if the lock has been poisoned, i.e. a panic occurred in another thread which has holding the lock - this a) shouldn't be happening and b) is probably unrecoverable.

**Comment by Westwooo** [comment]
@chvck What about the numerous `engine_state.ctrlc.as_ref().unwrap().clone();` ?
