### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [couchbaselabs/couchbase-shell#291]
👋 need a new release to get rid of some homebrew build patch (new release is good in general as well though). Thanks!

https://github.com/Homebrew/homebrew-core/blob/master/Formula/c/couchbase-shell.rb#L11-L15

**Comment by chvck** [comment]
Thanks for pointing this out @chenrui333 we're planning on doing a new release soon so we'll make sure to remove that.

**Comment by chenrui333** [comment]
glad to know, thanks @chvck!
