### ISSUE TITLE
Cloud shell

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#3]
- Users shouldn't need to edit connstrings in the config, should be able to highlevel edit whether or not to use TLS and the like.  
- Identify the right timeouts for good UX, default to those
- Handle CA certs better via configuration

**Comment by daschl** [comment]
let's make sure the tls / cert stuff is well handled and streamlined, add an example on how to use it wit cloud

**Comment by daschl** [comment]
the current shell works with cloud, the timeouts should also be okay. But there is an issue with commands like nodes / buckets which do not work through lcb

**Comment by ingenthr** [comment]
For example, 
/pools/default 

Connection times out, but using CURL is working.

Need help from the cloud team to see what's happening from the server side.

**Comment by daschl** [comment]
Fixed by applying a libcouchbase change to couchbase-rs
