### ISSUE TITLE
Make cbshell work correctly with CB instances in local Docker containers

### ISSUE THREAD

**Issue by okuzmin** [couchbaselabs/couchbase-shell#33]
It appears that the default cluster connection (localhost / Administrator / password) works with CB on Docker, with mapped local ports.  However, trying to execute basic commands after selecting a bucket (like "kv get") ends up in the looped error, like on the screenshot.

![cbshell-docker](https://user-images.githubusercontent.com/10153336/83748763-9973ec00-a65a-11ea-8355-f554aa557818.jpg)

![cbshell-docker2](https://user-images.githubusercontent.com/10153336/83748903-c9bb8a80-a65a-11ea-9676-8fa232182dd9.jpg)

**Comment by daschl** [comment]
It works for me with a single-node docker container.. the IP addresses point to something about the 2-node docker setup with IP addresses.. I'll close this one out for now, please reopen if you see an issue with single node as well and/or your network setup is fine and you can connect with another sdk properly?
