### ISSUE TITLE
cannot express config with alternate ports

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#47]
Scenario:

I'm trying to run both Couchbase 6.5 and 6.6 as single-node docker containers across the network.  Obviously, only one can use the canonical port of 11210.  In my current case, I have 6.5 with docker port mapping 11210 -> 11310 and 6.6 using 11210 -> 11210.

What I found with the following config was that even though I had a port number in there, it would ignore the port number and use port 11210 regardless.  This had the effect of `doc upsert …` to the wrong cluster.

Observed behavior:
No way to provide a port number.

Expected behavior:
There is a way to provide a port number.

Recommendations:
Earlier we allowed a connstr.  I think it would be good to do that again somehow since it allows simple expression of a lot of detail.  Right now, one cannot.

```
version = 1

[clusters.local]
hostnames = ["127.0.0.1"]
default-bucket = "default"

#[clusters."cbcloud.test"]
#hostnames = ["0cb55b31-d7ac-4ba3-8299-4d2cbc75f2df.dp.cloud.couchbase.com"]
#default-bucket = "travel-sample"
#cert-path = "/Users/ingenthr/.cbsh/ingenthr-test-ingenthr-cluster-20200918-root-certificate.pem"

[clusters."test-6.6"]
hostnames = ["dnix.home.ingenthron.org"]
default-bucket = "default"

#[clusters."test-CC"]
#hostnames = ["centos7lx-1.home.ingenthron.org"]
#default-bucket = "travel-sample"

[clusters."test-6.5"]
hostnames = ["dnix.home.ingenthron.org:11310"]
default-bucket = "default"
```

Aside: it may also be handy to know via some display if the hostname was resolved as DNS SRV or DNS A/AAAA.

**Comment by chvck** [comment]
I think this is actually fixed now but requires the usage of the management port rather than memcached.
