### ISSUE TITLE
Add either a setting or command to get query metrics

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/couchbase-shell#51]
At the moment, when one issues a query, there are no metrics for how long the query took to execute or how many rows it returns.  Since this may be in the way of the pipeline, perhaps it'd be fine to stash the metrics or out-of-rows metadata somewhere for fetching with another command.  

```
query "SELECT foo FROM bar LIMIT 1"
  (…pipeline renders table)
query lastmetrics
  (…pipeline renders table)
```

There might be better solutions too, like a setting for getting metrics in the pipeline too which I think will generate another output.  Or a flag and a setting.

**Comment by Westwooo** [comment]
This will be solved with the addition of the metrics flag in: https://github.com/couchbaselabs/couchbase-shell/issues/295
