### ISSUE TITLE
Analytics query streaming

### ISSUE THREAD

**Issue by petrkozorezov** [couchbaselabs/couchbase-shell#535]
I have an analytics dataset with >100m rows and want to make a query over it and dump to parquet or csv for further analysis. Is it possible to do without intermediate storing in memory?

**Comment by Westwooo** [comment]
Hello @petrkozorezov, the easiest way to do this would be: 

```
analytics "your analytics query here" | save results.csv
```

I believe that save will stream the data without collection.

**Comment by petrkozorezov** [comment]
It doesn't look like a streaming. It download first, then eats a lot of memory, and then writes everything to disk.
In my case it works with 5 columns and 60m rows (using around 60Gb ram), but doesn't with 80m (because of OOM killer) (the same query but with different 'limit').

**Comment by Westwooo** [comment]
You're correct, I think it could be possible to add support for streaming to the analytics command, I'll leave this issue up as a request for that feature.

**Comment by petrkozorezov** [comment]
related #162

**Comment by Westwooo** [comment]
This will be in the next release, please let us know if you run into any issues with is @petrkozorezov

**Comment by petrkozorezov** [comment]
> This will be in the next release, please let us know if you run into any issues with is @petrkozorezov

I've built the latest version from master.
Type is stream now, but behavior hasn't changed.

was:
```
> analytics "SELECT META().id FROM my_table LIMIT 10" | describe
table<id: string, cluster: string>
```

now:
```
> analytics "SELECT META().id FROM my_table LIMIT 10" | describe
table<id: string, cluster: string> (stream)
```

I tried a query, but it ate all memory (>120Gb) and then stuck.
```
> analytics "SELECT my_fields FROM my_table" | to csv | save --raw -f test.csv
```

**Comment by Westwooo** [comment]
> > This will be in the next release, please let us know if you run into any issues with is @petrkozorezov
> 
> I've built the latest version from master. Type is stream now, but behavior hasn't changed.
> 
> was:
> 
> ```
> > analytics "SELECT META().id FROM my_table LIMIT 10" | describe
> table<id: string, cluster: string>
> ```
> 
> now:
> 
> ```
> > analytics "SELECT META().id FROM my_table LIMIT 10" | describe
> table<id: string, cluster: string> (stream)
> ```
> 
> I tried a query, but it ate all memory (>120Gb) and then stuck.
> 
> ```
> > analytics "SELECT my_fields FROM my_table" | to csv | save --raw -f test.csv
> ```

Can you try without the `to csv` in the middle?

**Comment by Westwooo** [comment]
> stream

Can you try without the `to csv` in the middle, the save with a csv file name should be handle the conversion

**Comment by petrkozorezov** [comment]
> @petrkozorezov can you try without the `to csv` in the middle, the save with a csv file name should be handle the conversion

The same. It collects data in memory.

**Comment by Westwooo** [comment]
@petrkozorezov Can you try the save command with the `--raw` flag?

**Comment by petrkozorezov** [comment]
> @petrkozorezov Seems that when not using the `--raw` flag save reads the whole stream into memory. I will raise an issue to allow analytics to return csv that can be saved without converting. Could you try using the `--raw` flag without any extension on the file to see if this works?
```
> analytics "SELECT my_fields FROM my_table" | save -f --raw test
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #15:1:1]
 1 │ analytics "SELECT my_fields FROM my_table" | save -f --raw test
   · ────┬────
   ·     ╰── can't convert record<my_fields_with_types> to string
   ╰────
```

Without `--raw` the same error.

**Comment by Westwooo** [comment]
Ah makes sense, I will raise an issue to add the ability for analytics to return the results as csv.

**Comment by petrkozorezov** [comment]
It looks like it may work with polars and lazy dataframe, eg `analytics "SELECT my_fields FROM my_table" | polars into-lazy | polars save test.csv`, but it needs nu > 0.95 (I don't know which exacly, but in `0.99.1` `polars save` exists)

**Comment by Westwooo** [comment]
Nice I will have a look at updating the nu version.

**Comment by petrkozorezov** [comment]
@Westwooo I've tried PR #558, and streaming looks the same 🙈

It downloads everything to memory first and then dump it to file.
```
> analytics "SELECT my_fields FROM my_table" | polars into-lazy | polars save "test.csv"
```

And this command doesn't work as expected too.
```
> 1..100000 | each { |i| sleep 1ms; {i: $i} } | polars into-lazy | polars save test.csv
```

And this.
```
1..100000 | each { |i| sleep 1ms; {i: $i} } | to csv | save --raw -f test.txt
```

And the only one which works is this.
```
1..100000 | each { |i| sleep 1ms; $i } | save --raw -f test.txt
```

**Comment by Westwooo** [comment]
@petrkozorezov Yes I was trying a few things yesterday and got the same results unfortunately. I was surprised that none of the polars commands worked. `to csv` does: 

```
  // Check to ensure the input is likely one of our supported types first. We can't check a stream
  // without consuming it though
  match input {
      PipelineData::Value(Value::List { .. } | Value::Record { .. }, _) => (),
      PipelineData::Value(Value::Error { error, .. }, _) => return Err(*error),
      PipelineData::Value(other, _) => {
          return Err(make_unsupported_input_error(other.get_type(), head, span))
      }
      PipelineData::ByteStream(..) => {
          return Err(make_unsupported_input_error("byte stream", head, span))
      }
      PipelineData::ListStream(..) => (),
      PipelineData::Empty => (),
  }
```

Hence that reading to memory. Then as you found doing any conversion as part of save using the file ending also does a conversion that reads to memory. I'm going to dig into the Nushell code to see if there is the possibility of converting the data without reading to memory, else the solution might be allowing `analytics` to return csv directly.

**Comment by petrkozorezov** [comment]
@Westwooo I opened an issue on Nushell
https://github.com/nushell/nushell/issues/14338

**Comment by Westwooo** [comment]
@petrkozorezov I spoke to the nushell folks who told me to use the columns flag for `to csv`, this works:

```
1..100000 | each { |i| sleep 1ms; {i: $i} } | to csv --columns [i] | save testing.csv --raw
```

**Comment by petrkozorezov** [comment]
> @petrkozorezov I spoke to the nushell folks who told me to use the columns flag for `to csv`, this works:
> 
> ```
> 1..100000 | each { |i| sleep 1ms; {i: $i} } | to csv --columns [i] | save testing.csv --raw
> ```
> 
> Seems the stream is consumed to determine the columns, since I guess the results may not be uniform.

It works!!! 🎉
