### ISSUE TITLE
Add support for scopes/collections

### ISSUE THREAD

**Issue by chvck** [couchbaselabs/couchbase-shell#67]
- [x]  ├── analytics.rs (possible via statement itself though I think)
- [x]  ├── doc_get.rs
- [x]  ├── doc_insert.rs
- [x]  ├── doc_remove.rs
- [x]  ├── doc_replace.rs
- [x]  ├── doc_upsert.rs
- [x]  ├── query.rs

- [x]  ├── collections management

**Comment by daschl** [comment]
Two parts are needed per discussion:

 - scope level queries for n1ql and analytics
 - add simple management capabilities (adding and removing scopes and collections)
