### ISSUE TITLE
Change help msg first line?

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/couchbase-shell#68]
When using the help command, it says...

    > help
    Welcome to Nushell.

Perhaps it should instead say "Welcome to couchbase.sh (powered by Nushell)" or equivalent to be less confusing?

**Comment by chvck** [comment]
Just had a quick look into this. We'll need to either write our own help command or make some modifications to nu to do it (that string is hardcoded into the nushell `help` command) but I'm unsure we could continue to support `help commands` correctly without going the modifying nu route.

**Comment by chvck** [comment]
```
> help
Welcome to Couchbase Shell, powered by Nushell. Shell Yeah!
```
