### ISSUE TITLE
give a sane view of local couchbase log files?

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/couchbase-shell#70]
If I'm running couchbase server locally and using cbsh... would love to have a cbsh command that...

- opens the local couchbase server log files

- and merges them by timestamp

- optionally like tail -f to follow what's going on

so that i can grep through the trail of evidence using cbsh.

- and, fantasy -- cbsh can optionally apply to the ongoing log stream some library of well-tended diagnostic patterns or recipes to tell me why the #@#$*&^ my app is getting that inscrutable error and why that API ain't working right for me.

- and, fantasy x2 -- tell me some hints of what I probably did wrong as an app developer with the API.

**Comment by ingenthr** [comment]
The project for that is couchbaselabs/observability (a.k.a. CMOS).  That'll be coming soon.  It goes all the way through fantasy bullet #1.
