### ISSUE TITLE
libcouchbase can't bootstrap

### ISSUE THREAD

**Issue by bwgjoseph** [couchbaselabs/couchbase-shell#73]
Running on Windows 10, gotten the shell to work but unable to issue most commands.

Am running `Enterprise Edition 6.6.0 build 7909` via docker

![image](https://user-images.githubusercontent.com/37484538/99551520-e70cc700-29f6-11eb-8b92-085e8b081782.png)

Let me know what more info to provide

**Comment by chvck** [comment]
@bwgjoseph I'm having a bit of trouble reproducing this, it's interesting that you don't see more log output alongside the timeout, usually I'd expect to see some follow up logs giving a bit more detail. Just to check some basics, can you connect OK directly via one of the SDKs?

**Comment by bwgjoseph** [comment]
Yup, I'm inside the UI.. and created the data via `ottoman` with no issue.

![image](https://user-images.githubusercontent.com/37484538/99561871-6784f500-2a02-11eb-9afa-e986e6d1f8fa.png)

**Comment by chvck** [comment]
Could you try run `RUST_LOG=debug .\cbsh.exe ...` please @bwgjoseph that should give us the full libcouchbase log output.

**Comment by bwgjoseph** [comment]
It doesn't seem to output anything.

I assume it's setting for env var so I did a `SET RUST_LOG= debug` 

![image](https://user-images.githubusercontent.com/37484538/99680698-4ed71680-2ab8-11eb-8138-77985c5ff27a.png)

Let me know how to proceed.

**Comment by chvck** [comment]
That's right, I just tried `SET RUST_LOG=debug && cbsh.exe` and for some reason that didn't output any logs but if I did `SET RUST_LOG=debug` and then as the next command ran `cbsh.exe` then it did output the logs. Setting the RUST_LOG to debug should output a whole bunch of nushell logging as well as couchbase logs.

**Comment by bwgjoseph** [comment]
Alright, weird that the first time I tried on separate line it doesn't work. But it does now. Might have typed wrongly earlier on. So here goes.

Connecting..

```js
Z:\Development\Tools\cb>.\cbsh.exe --username admin --hostnames 127.0.0.1 -p
 DEBUG cbsh > Effective CliOptions { hostnames: Some("127.0.0.1"), ui: false, username: Some("admin"), password: true, cluster: None, bucket: None, scope: None, collection: None, command: None, script: None, stdin: false, no_motd: false, cert_path: None }
 DEBUG cbsh::config > Could not locate "Z:\\Development\\Tools\\cb\\.cbsh\\config" becaue of Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
 DEBUG cbsh::config > Could not locate "C:\\Users\\Joseph\\.cbsh\\config" becaue of Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
 DEBUG cbsh::config > Could not locate "Z:\\Development\\Tools\\cb\\.cbsh\\credentials" becaue of Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
 DEBUG cbsh::config > Could not locate "C:\\Users\\Joseph\\.cbsh\\credentials" becaue of Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
 WARN  cbsh         > Config ShellConfig { version: 1, clusters: {} }
```

After input password...

```js
Password:
 DEBUG couchbase::io::lcb > Using libcouchbase IO transport
 INFO  couchbase::io::lcb::callbacks > Version=0.3.0_175_g463b902475, Changeset=463b902475caa30f7e39da2c99c3d0ba31658bb5
 INFO  couchbase::io::lcb::callbacks > Effective connection string: couchbase://127.0.0.1?operation_timeout=30&config_total_timeout=30&config_node_timeout=30&query_timeout=75. Bucket=(null)
 DEBUG reqwest::connect              > starting new connection: http://couchbase.sh/
 DEBUG hyper::client::connect::dns   > resolving host="couchbase.sh"
 DEBUG couchbase::io::lcb::callbacks > Applying initial cntl operation_timeout=30
 DEBUG couchbase::io::lcb::callbacks > Applying initial cntl config_total_timeout=30
 DEBUG couchbase::io::lcb::callbacks > Applying initial cntl config_node_timeout=30
 DEBUG couchbase::io::lcb::callbacks > Applying initial cntl query_timeout=75
 INFO  couchbase::io::lcb::callbacks > DNS SRV lookup failed: LCB_ERR_UNKNOWN_HOST (1049). Ignore this if not relying on DNS SRV records
 DEBUG couchbase::io::lcb::callbacks > Adding host 127.0.0.1:8091 to initial HTTP bootstrap list
 DEBUG couchbase::io::lcb::callbacks > Adding host 127.0.0.1:11210 to initial CCCP bootstrap list
 INFO  couchbase::io::lcb::callbacks > Requested network configuration: heuristic
 DEBUG couchbase::io::lcb::callbacks > Preparing providers (this may be called multiple times)
 DEBUG couchbase::io::lcb::callbacks > Provider CCCP is ENABLED
 DEBUG couchbase::io::lcb::callbacks > Provider HTTP is ENABLED
 DEBUG hyper::client::connect::http  > connecting to 185.199.108.153:80
 INFO  couchbase::io::lcb::callbacks > Requesting connection to node 127.0.0.1:11210 for CCCP configuration
 DEBUG couchbase::io::lcb::callbacks > <127.0.0.1:11210> (HE=00000208F48E0950) Creating new connection because none are available in the pool
 INFO  couchbase::io::lcb::callbacks > <127.0.0.1:11210> (SOCK=5680934722418685) Starting. Timeout=30000000us
 INFO  couchbase::io::lcb::callbacks > <127.0.0.1:11210> (SOCK=5680934722418685) Connected established
 INFO  couchbase::io::lcb::callbacks > <127.0.0.1:11210> (SOCK=5680934722418685) Couldn't set TCP_NODELAY
 INFO  couchbase::io::lcb::callbacks > <127.0.0.1:11210> (SOCK=5680934722418685) Couldn't set TCP_KEEPALIVE
 DEBUG couchbase::io::lcb::callbacks > <127.0.0.1:11210> (HE=00000208F48E0950) Received result for I=00000208F48F6500,C=0000000000000000; E=0x0
 DEBUG couchbase::io::lcb::callbacks > <127.0.0.1:11210> (HE=00000208F48E0950) Assigning R=00000208F48DE6E0 SOCKET=00000208F48F5CE0
 DEBUG hyper::client::connect::http  > connected to 185.199.108.153:80
 DEBUG couchbase::io::lcb::callbacks > <127.0.0.1:11210> (CTX=00000208F48F4180,unknown) Pairing with SOCK=5680934722418685
 DEBUG hyper::proto::h1::io          > flushed 94 bytes
 DEBUG couchbase::io::lcb::callbacks > <127.0.0.1:11210> (CTX=00000208F48F4180,sasl,SASLREQ=00000208F48F3FD0) HELO identificator: {"a":"libcouchbase/0.3.0_175_g463b902475 (Windows-10.0.14393; AMD64; MSVC 19.16.27043.0)","i":"9ca3d653b5ac496e/5680934722418685"}, features: 0x02 (TLS), 0x06 (XATTR), 0x0b (JSON), 0x08 (Select bucket), 0x07 (XERROR), 0x03 (TCP nodelay), 0x0a (Snappy), 0x04 (Mutation seqno), 0x0f (Tracing), 0x12 (Collections), 0x0e (Unordered execution), 0x17 (Create as Deleted)
 DEBUG couchbase::io::lcb::callbacks > <127.0.0.1:11210> (CTX=00000208F48F4180,sasl,SASLREQ=00000208F48F3FD0) Server supports features: 0x03 (TCP nodelay), 0x04 (Mutation seqno), 0x06 (XATTR), 0x07 (XERROR), 0x08 (Select bucket), 0x0a (Snappy), 0x0b (JSON), 0x0e (Unordered execution), 0x0f (Tracing), 0x17 (Create as Deleted)
 DEBUG hyper::proto::h1::io          > read 1460 bytes
 DEBUG hyper::proto::h1::io          > parsed 19 headers
 DEBUG hyper::proto::h1::conn        > incoming body is content-length (9339 bytes)
 DEBUG reqwest::async_impl::client   > response '404 Not Found' for http://couchbase.sh/motd
 DEBUG hyper::proto::h1::io          > read 8192 bytes
 WARN  couchbase::io::lcb::callbacks > <127.0.0.1:11210> (CTX=00000208F48F4180,sasl,SASLREQ=00000208F48F3FD0) SASL PLAIN authentication is not allowed on non-TLS connections
 DEBUG hyper::proto::h1::io          > read 330 bytes
 DEBUG hyper::proto::h1::conn        > incoming body completed
 DEBUG hyper::client::pool           > pooling idle connection for ("http", couchbase.sh)
 DEBUG cbsh                          > Could not request MOTD because converting the response data failed: error decoding response body: expected value at line 1 column 1
 DEBUG rustyline                     > ANSI colors already enabled
 DEBUG rustyline                     > Changeset::delete(0, "")
 DEBUG rustyline                     > Changeset::insert_str(0, "")
 DEBUG rustyline                     > old layout: Layout { prompt_size: Position { col: 0, row: 0 }, default_prompt: false, cursor: Position { col: 0, row: 0 }, end: Position { col: 0, row: 0 } }
 DEBUG rustyline                     > new layout: Layout { prompt_size: Position { col: 2, row: 1 }, default_prompt: true, cursor: Position { col: 2, row: 1 }, end: Position { col: 2, row: 1 } }
```

Type `nodes` command

```js
> nodes DEBUG rustyline                     > Changeset::begin
 DEBUG rustyline                     > Changeset::end

 DEBUG nu_cli::cli                   > === Parsed ===
 DEBUG nu_cli::cli                   > LiteBlock {
    block: [
        LitePipeline {
            commands: [
                LiteCommand {
                    name: Spanned {
                        span: Span {
                            start: 0,
                            end: 5,
                        },
                        item: "nodes",
                    },
                    args: [],
                },
            ],
        },
    ],
}
 DEBUG nu_cli::cli                   > ClassifiedBlock {
    block: Block {
        block: [
            Commands {
                list: [
                    Internal(
                        InternalCommand {
                            name: "nodes",
                            name_span: Span {
                                start: 0,
                                end: 5,
                            },
                            args: Call {
                                head: SpannedExpression {
                                    expr: Command,
                                    span: Span {
                                        start: 0,
                                        end: 5,
                                    },
                                },
                                positional: None,
                                named: Some(
                                    NamedArguments {
                                        named: {
                                            "help": AbsentSwitch,
                                            "clusters": AbsentValue,
                                        },
                                    },
                                ),
                                span: Span {
                                    start: 0,
                                    end: 5,
                                },
                                external_redirection: None,
                            },
                        },
                    ),
                ],
                span: Span {
                    start: 0,
                    end: 5,
                },
            },
        ],
        span: Span {
            start: 0,
            end: 5,
        },
    },
    failed: None,
}
 WARN  couchbase::io::lcb::instance  > Cannot dispatch operation because no open bucket found!
error: Error: Couchbase SDK Error: The request has been canceled: {"cause":"No active libcouchbase instance found to handle the request! Did bootstrap fail?"}

 DEBUG rustyline                     > ANSI colors already enabled
 DEBUG rustyline                     > Changeset::delete(0, "")
 DEBUG rustyline                     > Changeset::insert_str(0, "")
 DEBUG rustyline                     > old layout: Layout { prompt_size: Position { col: 0, row: 0 }, default_prompt: false, cursor: Position { col: 0, row: 0 }, end: Position { col: 0, row: 0 } }
 DEBUG rustyline                     > new layout: Layout { prompt_size: Position { col: 2, row: 1 }, default_prompt: true, cursor: Position { col: 2, row: 1 }, end: Position { col: 2, row: 1 } }
👤 admin at 🏠 default
```

Hope it helps!

**Comment by chvck** [comment]
Thanks @bwgjoseph that has helped. It looks like libcouchbase is refusing to sending the auth request because it thinks that only PLAIN auth is available (we typically don't allow that unless a) over a tls connection or b) forced). This is going to require a bit of investigation to try to work out why libcouchbase doesn't think any other auth methods are available - possibly something related to openssl and static linking again.

**Comment by bwgjoseph** [comment]
Alright, let me know if you need my help to run/test anything

**Comment by chvck** [comment]
Hi @bwgjoseph could you try the debug build at https://github.com/couchbaselabs/couchbase-shell/runs/1452755496?check_suite_focus=true please? Note that the connection will be authenticated over PLAIN and you'll get a message to inform you of that. On my machine I can use couchbase-shell correctly though.

**Comment by bwgjoseph** [comment]
Hi @chvck,

Seem to be connecting and able to issue some commands

This is the error message I gotten

> ERROR couchbase::io::lcb::callbacks > <127.0.0.1:11210> (CTX=000001D13D20A6B0,sasl,SASLREQ=000001D13D20A450) SASL PLAIN authentication is not allowed on non-TLS connections. But this libcouchbase compiled without OpenSSL, therefore PLAIN is the only option. The library will fallback to PLAIN, but using SCRAM methods is strongly recommended over non-encrypted transports.

What does it actually mean? I have to connect over SSL (by right)? 

---

But when I try `doc` command, it doesn't seem to work. Am I doing it wrong?

I have the following doc in my `testBucket`

![image](https://user-images.githubusercontent.com/37484538/100251389-ad4d3a80-2f79-11eb-9f60-f6a210191263.png)

When I tried to get the doc, it has no error or anything

![image](https://user-images.githubusercontent.com/37484538/100251442-be964700-2f79-11eb-895b-88a4a5ee8a13.png)

When I tried to upsert, it also fail

![image](https://user-images.githubusercontent.com/37484538/100251502-cfdf5380-2f79-11eb-94fc-a4e2d21272d0.png)


I'm following the [docs](http://couchbase.sh/docs/#_reading_and_writing_documents)

**Comment by chvck** [comment]
Hi @bwgjoseph, sorry that you're having a bit of a hard time getting this working correctly.

> What does it actually mean? I have to connect over SSL (by right)?

Basically, our SDKs (couchbase-shell is built on top of the unofficial and work in progress rust SDK) do not allow non-TLS connections to authenticate using PLAIN by default - they require the use of SCRAM. This is a configuration option in the SDKs and libcouchbase also falls back to PLAIN if it cannot find openssl which it needs for SCRAM. If you connect over SSL then we do allow PLAIN by default. This message is just something that has been added to warn users that they might be open to attacks. We will get this fixed in couchbase-shell once we get the linking working correctly.

If you run `doc upsert my-doc {"hello":"world"} --bucket testBucket | get failures` what do you see? I have a theory that I know what's happening but I can't explain why yet.

**Comment by bwgjoseph** [comment]
It's alright, no worries. 

Thanks for the explanation too!

---

Somehow, it seem to be working this time, I have no idea why. But, after running the `upsert` command, I typed in a wrong command `doc get he --bucket test` instead of `testBucket`, and this error kept coming up

![image](https://user-images.githubusercontent.com/37484538/100371586-fc12d700-3042-11eb-8777-547eed6e533f.png)

I tried to kill it using `ctrl + c` but it just kept going until it seem to stop here

![image](https://user-images.githubusercontent.com/37484538/100371673-1cdb2c80-3043-11eb-8c9f-55b76c4103bd.png)

---

Now that I open up a new command prompt, login and ran `doc get he --bucket testBucket`, it hangs there, and I have to kill it again.

![image](https://user-images.githubusercontent.com/37484538/100371846-5ca21400-3043-11eb-8646-46882bbdefb5.png)

I tried to run `doc get he --bucket testBucket | get failures` but doesn't seem to have anything.

Then I tried your command again, and for some reason, it didn't seem to run.

![image](https://user-images.githubusercontent.com/37484538/100371985-92df9380-3043-11eb-9a12-8e262bde9bae.png)

Somehow, the first time succeeded but only once

Let me know if you need to to try out anything else

**Comment by chvck** [comment]
> Somehow, it seem to be working this time, I have no idea why. But, after running the upsert command, I typed in a wrong command doc get he --bucket test instead of testBucket, and this error kept coming up

The SDKs automatically retry bucket not found errors until either they find the bucket or that `cluster` SDK instance is shutdown, something that we probably need to handle or at least surface better in cbshell, at least making ctrl-c work.

> I tried to run doc get he --bucket testBucket | get failures but doesn't seem to have anything.

Failures is column which we have added for mutation commands (e.g. upsert) but doesn't exist for `get` which is why you don't see anything there.

I see similar behaviour to you only when I run cbshell in Windows, sometimes it just hangs and sometimes I get that Unknown Error. For some reason Wireshark is refusing to show the packets related to key value operations (it's possible they aren't actually getting sent I guess) for when it hangs, for Unknown Error I have seen a packet a couple of times and it looks like libcouchbase is trying to fetch the collection id for the _default collection (which shouldn't happen, especially against server versions that do not support collections). I might have a fix for that though which will make the shell usable whilst I dig into why this happens.

**Comment by bwgjoseph** [comment]
Sure, ping me anytime when you have a newer build for me to test it out

Thank you for your effort

**Comment by chvck** [comment]
@bwgjoseph I have a theory that this is somehow related to using the `--bucket` flag. Could you possibly try by using a config file which has a `default-bucket` in it rather than passing flags to cbsh and then using `--bucket` within it? The config file just needs to be a file called `config` within a directory called `.cbsh` in the same dir as the binary. See: [http://couchbase.sh/docs/#_config_file_format](http://couchbase.sh/docs/#_config_file_format). Hopefully doing that will help to pinpoint where the issue lies.

**Comment by bwgjoseph** [comment]
I created a file `config` at the root of the directory with `cbsh.exe` and this is the content

```
[clusters.default]
hostnames = ["127.0.0.1"]
default-bucket = "testBucket"
# The following can be part of the config or credentials
username = "admin"
password = "password"
```

And the commands I tried

![image](https://user-images.githubusercontent.com/37484538/101071417-8e812080-35d7-11eb-9adf-6795ebef268b.png)

---

I tried to run with `debug` mode and ran this command `doc get aaa --bucket testBucket | get failures`

![image](https://user-images.githubusercontent.com/37484538/101072036-59c19900-35d8-11eb-9c3b-ad41780579f7.png)

---

And then I continued to try to run this `doc upsert my-doc {"hello":"world"} --bucket testBucket | get failures` and this is the result which seem to be successful as I can see the doc created inside the UI

```
DEBUG rustyline                     > Changeset::begin
 DEBUG rustyline                     > Changeset::end

 DEBUG nu_cli::cli                   > === Parsed ===
 DEBUG nu_cli::cli                   > LiteBlock {
    block: [
        LitePipeline {
            commands: [
                LiteCommand {
                    name: Spanned {
                        span: Span {
                            start: 0,
                            end: 3,
                        },
                        item: "doc",
                    },
                    args: [
                        Spanned {
                            span: Span {
                                start: 4,
                                end: 10,
                            },
                            item: "upsert",
                        },
                        Spanned {
                            span: Span {
                                start: 11,
                                end: 17,
                            },
                            item: "my-doc",
                        },
                        Spanned {
                            span: Span {
                                start: 18,
                                end: 35,
                            },
                            item: "{\"hello\":\"world\"}",
                        },
                        Spanned {
                            span: Span {
                                start: 36,
                                end: 44,
                            },
                            item: "--bucket",
                        },
                        Spanned {
                            span: Span {
                                start: 45,
                                end: 55,
                            },
                            item: "testBucket",
                        },
                    ],
                },
                LiteCommand {
                    name: Spanned {
                        span: Span {
                            start: 58,
                            end: 61,
                        },
                        item: "get",
                    },
                    args: [
                        Spanned {
                            span: Span {
                                start: 62,
                                end: 70,
                            },
                            item: "failures",
                        },
                    ],
                },
            ],
        },
    ],
}
 DEBUG nu_cli::cli                   > ClassifiedBlock {
    block: Block {
        block: [
            Commands {
                list: [
                    Internal(
                        InternalCommand {
                            name: "doc upsert",
                            name_span: Span {
                                start: 0,
                                end: 10,
                            },
                            args: Call {
                                head: SpannedExpression {
                                    expr: Command,
                                    span: Span {
                                        start: 0,
                                        end: 10,
                                    },
                                },
                                positional: Some(
                                    [
                                        SpannedExpression {
                                            expr: Literal(
                                                String(
                                                    "my-doc",
                                                ),
                                            ),
                                            span: Span {
                                                start: 11,
                                                end: 17,
                                            },
                                        },
                                        SpannedExpression {
                                            expr: Literal(
                                                String(
                                                    "{\"hello\":\"world\"}",
                                                ),
                                            ),
                                            span: Span {
                                                start: 18,
                                                end: 35,
                                            },
                                        },
                                    ],
                                ),
                                named: Some(
                                    NamedArguments {
                                        named: {
                                            "bucket": Value(
                                                Span {
                                                    start: 36,
                                                    end: 44,
                                                },
                                                SpannedExpression {
                                                    expr: Literal(
                                                        String(
                                                            "testBucket",
                                                        ),
                                                    ),
                                                    span: Span {
                                                        start: 45,
                                                        end: 55,
                                                    },
                                                },
                                            ),
                                        },
                                    },
                                ),
                                span: Span {
                                    start: 0,
                                    end: 55,
                                },
                                external_redirection: Stdout,
                            },
                        },
                    ),
                    Internal(
                        InternalCommand {
                            name: "get",
                            name_span: Span {
                                start: 58,
                                end: 61,
                            },
                            args: Call {
                                head: SpannedExpression {
                                    expr: Command,
                                    span: Span {
                                        start: 58,
                                        end: 61,
                                    },
                                },
                                positional: Some(
                                    [
                                        SpannedExpression {
                                            expr: Literal(
                                                ColumnPath(
                                                    [
                                                        Bare(
                                                            Spanned {
                                                                span: Span {
                                                                    start: 62,
                                                                    end: 70,
                                                                },
                                                                item: "failures",
                                                            },
                                                        ),
                                                    ],
                                                ),
                                            ),
                                            span: Span {
                                                start: 62,
                                                end: 70,
                                            },
                                        },
                                    ],
                                ),
                                named: Some(
                                    NamedArguments {
                                        named: {
                                            "help": AbsentSwitch,
                                        },
                                    },
                                ),
                                span: Span {
                                    start: 58,
                                    end: 70,
                                },
                                external_redirection: None,
                            },
                        },
                    ),
                ],
                span: Span {
                    start: 0,
                    end: 70,
                },
            },
        ],
        span: Span {
            start: 0,
            end: 70,
        },
    },
    failed: None,
}
 DEBUG rustyline                     > ANSI colors already enabled
 DEBUG rustyline                     > Changeset::delete(0, "")
 DEBUG rustyline                     > Changeset::insert_str(0, "")
 DEBUG rustyline                     > old layout: Layout { prompt_size: Position { col: 0, row: 0 }, default_prompt: false, cursor: Position { col: 0, row: 0 }, end: Position { col: 0, row: 0 } }
 DEBUG rustyline                     > new layout: Layout { prompt_size: Position { col: 2, row: 1 }, default_prompt: true, cursor: Position { col: 2, row: 1 }, end: Position { col: 2, row: 1 } }
```

And then I ran `doc get my-doc --bucket testBucket` and it seem to be returning my result

```
 DEBUG cbsh::cli::doc_get            > Running kv get for docs ["my-doc"]
 WARN  couchbase::io::lcb::encode    > Sending now
───┬────────┬─────────────────────┬─────────────
 # │   id   │         cas         │   content
───┼────────┼─────────────────────┼─────────────
 0 │ my-doc │ 1607020166740443136 │ [row hello]
───┴────────┴─────────────────────┴─────────────
 DEBUG rustyline                     > ANSI colors already enabled
 DEBUG rustyline                     > Changeset::delete(0, "")
 DEBUG rustyline                     > Changeset::insert_str(0, "")
 DEBUG rustyline                     > old layout: Layout { prompt_size: Position { col: 0, row: 0 }, default_prompt: false, cursor: Position { col: 0, row: 0 }, end: Position { col: 0, row: 0 } }
 DEBUG rustyline                     > new layout: Layout { prompt_size: Position { col: 2, row: 1 }, default_prompt: true, cursor: Position { col: 2, row: 1 }, end: Position { col: 2, row: 1 } }
```

And then I tried to grab other doc that is currently inside the bucket but it seem to hang again

![image](https://user-images.githubusercontent.com/37484538/101072496-19aee600-35d9-11eb-8329-81d2e2356ab8.png)

I ran `doc get aaa --bucket testBucket` and it just hangs here

![image](https://user-images.githubusercontent.com/37484538/101072547-27646b80-35d9-11eb-9670-20a1868a277c.png)

And lastly, I tried to `upsert` another doc and it also hangs without creating anything.

Seem very random to me, but let me know if there's anything that I have done wrongly, and if there's any specific command you like me to run, let me know.

**Comment by chvck** [comment]
Quick question @bwgjoseph as you're using localhost are you only running a single node cluster?

Really appreciate all of the help that you're giving us on this.

**Comment by bwgjoseph** [comment]
Yup, it's localhost, and single node cluster.

**Comment by chvck** [comment]
> I created a file config at the root of the directory with cbsh.exe and this is the content

The config file needs to go in a .cbsh directory alongside the cbsh.exe binary (or in your home directory).

> I tried to run with debug mode and ran this command doc get aaa --bucket testBucket | get failures

I think that this is actually good. The `doc get` command doesn't support a failures column, so it means that `doc get` returned and then `get failures` ran against the result.

I'm seeing issues running with `--bucket` cross platform and have filed a bug against libcouchbase for it. If you could get the config file working correctly and rerun that'd be great. An easy way to check if it's picking up the config file is to just run `cbsh.exe` without any flags. It should then pick up the username and password from your config file.

**Comment by bwgjoseph** [comment]
Hi @chvck,

Thanks for that, I actually misunderstood and placed `config` at the root directory. Have placed it in `.cbsh` directory now, and it seem to be working. I added `version` into `config` as well,  otherwise it will complain.

This is my current `config`

```js
version = 1

[clusters.default]
hostnames = ["127.0.0.1"]
default-bucket = "testBucket"
# The following can be part of the config or credentials
username = "admin"
password = "password"
```

So I ran couple commands and so far it is looking great!

![image](https://user-images.githubusercontent.com/37484538/101366490-fbe6c700-38df-11eb-8a66-3771390f7915.png)

Also tested one using `--bucket` command

![image](https://user-images.githubusercontent.com/37484538/101366638-220c6700-38e0-11eb-84f6-9a39ad75d660.png)

Seem like having `config` helps. I tried to remove `config` and run the commands again and it hangs on `doc get my-doc --bucket testBucket` again

**Comment by chvck** [comment]
Hi @bwgjoseph woohoo, glad to hear that you got it working. There is definitely a bug using the `--bucket` flag. I'll raise an issue for that. Are we OK to close this one now? I've captured the build issues in other tickets.

Thanks again for your assistance. It's much appreciated.

**Comment by bwgjoseph** [comment]
Is there a link to the issues you created? Or, maybe you can ping me here once that has been resolved so I can run further test.

Otherwise, please go ahead and close this issue. 

Thank you for your help!

**Comment by chvck** [comment]
Sure, the issues are:
https://github.com/couchbaselabs/couchbase-shell/issues/80
https://github.com/couchbaselabs/couchbase-shell/issues/72
https://github.com/couchbaselabs/couchbase-shell/issues/79

**Comment by bwgjoseph** [comment]
Thanks! Will close this issue
