### ISSUE TITLE
fake --list-functions error

### ISSUE THREAD

**Issue by amfrye777** [couchbaselabs/couchbase-shell#74]
fake command --list-functions for windows build provides an error

```
> fake --list-functions
error: Error: invalid escape at line 50 column 98
```

**Comment by chvck** [comment]
This has got something to do with serde_json not being able to parse the output from the `dirPath()` function. The output of dirPath() is something like:
[src\cli\fake_data\mod.rs:370] DirPath(EN).fake::<String>() = "/usr\\week\\oliver\\noah"

**Comment by chvck** [comment]
We now escape the strings for dirPath() and filePath().
